# config.yaml

# YOU MUST NOT CHANGE THE IDs for the databases

# db_path and destination_path must have the trailing slash
# defaultPath: humandb/
db_path: "humandb/"                                                 # Change this to take a different path for the databases

# defaultPath: result/
destination_path: "result/"                                         # Change this to take a different path for the Annotated VCF files

# Name of the DBs
databasesTXT:
  - id: Clinvar
    file: "clinvar"
    operation: "f"
  - id: OMIM
    file: "hg38_genemap2"
    operation: "f"
databasesGFF3: 
  - id: Gencode
    file: "gencode.v46.annotation.gff3"
    operation: "r"
databasesVCF:
  - id: gnomAD  
    file: "gnomad_chrY.vcf"
    operation: "f"
  - id: HGMD      
    file: "HGMD_Pro_2024.1_hg38.vcf"
    operation: "f"

# Prepare DB
removeDEL:                                                          # substitute <del> with the .
  - id: HGMD 

convertFromVCFToTxt:                                                # confert from VCF to TXT     
  - id: Clinvar 

clean:                                                              # Remove the comments from txt files
  - id: OMIM

# Scraping
autoCheck: false

scraping:
  - id: Gencode
    release: "44"
    website: "https://www.gencodegenes.org/human"
    textToSearch: "Release "
    tag: "h1"
  - id: Clinvar
    date: "2024-04-22"
    website: "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/"
    textToSearch: "clinvar_"
    tag: "a"
  - id: GnomAD
    release: "4.1"
    website: "https://gnomad.broadinstitute.org/news/category/release/"
    textToSearch: "gnomAD"
    tag: "h2"
  - id: OMIM
    date: "2024-09-20"
    website: "https://omim.org"
    textToSearch: "Updated "
    tag: "h5"
