# config.yaml

# defaultPath: humandb/
db_path: "humandb/" #Change this to take a different path for the databases

# defaultPath: result/
destination_path: "result/" #Change this to take a different path for the Annotated VCF files

# nameOfDB
#TODO: Add doc for the nomencalture of the databases

databasesTXT:
  - id: Clinvar
    file: "convertito"
  - id: OMIM
    file: "omim"
databasesVCF:
  #- id: genomAD
  #file: "hg38_gnomad.vcf"
databasesGFF3:
  #- id: Gencode
  #file: "hg38_gencode.gff3"
  #- id: HGMD
  #  file: "hg38_hgmd.gff3"
