# config.yaml

#YOU MUST NOT CHANGE THE ID

# db_path and destination_path must have the trailing slash
# defaultPath: humandb/
db_path: "humandb/" #Change this to take a different path for the databases

# defaultPath: result/
destination_path: "result/" #Change this to take a different path for the Annotated VCF files

# nameOfDB
databasesTXT:
  - id: Clinvar
    file: "clinvar"
    operation: "f"
  - id: OMIM
    file: "omim"
    operation: "f"
databasesVCF: # ;
  - id: gnomAD  #this ID must be unchanged
    file: "hg38_gnomadExomesY.vcf"
    operation: "f"
  - id: HGMD      #this ID must be unchanged
    file: "hg38_hgmd.vcf"
    operation: "f"
databasesGFF3: # ,
  - id: Gencode
    file: "hg38_gencode.gff3"
    operation: "r"

#Prepare DB
removeDEL:
  - id: HGMD # substitute <del> with the .
    path: "humandb/hg38_HGMD.vcf"

pathClinvar: "humandb/hg38_clinvar.vcf" #convert from .vcf to .txt

clean:  #remove the #comment from the file
  - id: OMIM
    path: "humandb/hg38_omim.txt"

# Scraping
autoCheck: false

scraping:
  - id: Gencode
    release: "44"
    date: "12.2023"
    genVersion: "GRCh38"
  - id: Clinvar
    name: "clinvar.vcf.gz"
    date: "2024-04-22"
  - id: GnomAD
    release: "4.0"
  - id: OMIM
    date: "2024-04-16"
